version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: movie-recommender
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0